### ISSUE TITLE
把 team 改成圓形的圖示,利用翻卡的方式顯示資訊

### ISSUE THREAD

**Issue by calee0219** [NCTU-ToolBox/ToolBox#6]
希望滑鼠移到圓形頭貼後就會方卡, 顯示資訊, 滑鼠移開後翻回

**Comment by 5teven1in** [comment]
是像youtube影片的訂閱紐一樣嗎
https://youtu.be/-ncbiKZVUz4?t=8m19s

**Comment by calee0219** [comment]
應該比較像這個
http://www.xiaobao1993.com/486.html
不過它的特效感覺還是不夠立體
或這個
http://codepen.io/frank890417/pen/woeEdJ?editors=0101
不過要怎麼直接在對話下面留言啊 @@a

**Comment by calee0219** [comment]
現在變成要考慮到底圓形的頭貼資訊量會不會太少或要再用其他方式顯示資訊了 XDD

**Comment by oalieno** [comment]
差不多了
