### ISSUE TITLE
在 title pic 的中間加入文字, 試著利用打字特效

### ISSUE THREAD

**Issue by calee0219** [NCTU-ToolBox/ToolBox#9]
文字先隨便打ㄅ, 例如 "Hi, we are ToolBox team from NCTU. We are a team of students. And we'll glad to help you!!"
三句換行出現, 不要同時出現

好像已經有寫好的 js 可以用
https://github.com/mattboldt/typed.js/

**Comment by 5teven1in** [comment]
做好了唷 只是字型還要在挑一下比較好
